state.cache["/"] = {
  comments: [
    {
      create_date: "2024-06-23T18:49:56.669Z",
      comment_id: "1",
      body: "Your local food bank would be a good place to start.",
      note: null,
      parent_comment_id: null,
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        comment_id: "1",
      },
    },
    {
      create_date: "2024-06-23T19:07:18.674Z",
      comment_id: "2",
      body: "Has anyone else seen the anime Trigun? With Vash the Stampede?",
      note: "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
      parent_comment_id: null,
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        comment_id: "2",
      },
    },
    {
      create_date: "2024-06-23T19:33:17.838Z",
      comment_id: "3",
      body: "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
      note: "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
      parent_comment_id: null,
      display_name: "John Doe",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        comment_id: "3",
      },
    },
    {
      create_date: "2024-06-27T00:56:22.121Z",
      comment_id: "5",
      body: "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
      note: null,
      parent_comment_id: "2",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-27T01:12:35.526Z",
      comment_id: "6",
      body: "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
      note: null,
      parent_comment_id: "5",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-27T01:32:34.262Z",
      comment_id: "7",
      body: "Is that where the greatest need is?",
      note: null,
      parent_comment_id: "1",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-27T01:32:55.746Z",
      comment_id: "8",
      body: "Is that where you could have the most impact?",
      note: null,
      parent_comment_id: "1",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-27T01:34:54.927Z",
      comment_id: "9",
      body: "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
      note: null,
      parent_comment_id: "8",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-27T02:32:12.524Z",
      comment_id: "11",
      body: "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
      note: null,
      parent_comment_id: "6",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: "e2de6604-a453-4f52-93e2-95f3b5347cb2",
      $comment: {},
    },
    {
      create_date: "2024-06-27T02:45:11.760Z",
      comment_id: "12",
      body: "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
      note: null,
      parent_comment_id: "9",
      display_name: "Derek",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {},
    },
    {
      create_date: "2024-06-28T05:57:17.093Z",
      comment_id: "13",
      body: "You are committing the greatest sin. You will regret this.",
      note: "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
      parent_comment_id: "3",
      display_name: "John Doe",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-28T05:58:16.962Z",
      comment_id: "14",
      body: "I’m not being aggressive, I’m informing of you of facts.",
      note: "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
      parent_comment_id: "13",
      display_name: "John Doe",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {
        $expand_button: {},
      },
    },
    {
      create_date: "2024-06-28T06:02:12.940Z",
      comment_id: "15",
      body: "I’m not being judgmental, I’m saying God will judge you.",
      note: "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
      parent_comment_id: "14",
      display_name: "John Doe",
      display_name_index: "0",
      edit: false,
      image_uuids: null,
      $comment: {},
    },
  ],
  topics: [
    {
      create_date: "2024-07-07T22:24:35.556Z",
      topic_id: "3",
      title: "What can be done to demonstrate unconditional love for all?",
      slug: "What_can_be_done_to_demonstrate_unconditional_love_for_all",
      body: "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
      comment_count: "0",
      comment_count_max_create_date: "2024-07-19T04:36:35.761Z",
      edit: false,
      image_uuids: null,
      $topic: {},
    },
    {
      create_date: "2024-07-07T22:24:28.401Z",
      topic_id: "5",
      title: "The Bible",
      slug: "The_Bible",
      body: "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
      comment_count: "0",
      comment_count_max_create_date: "2024-07-19T04:36:35.761Z",
      edit: false,
      image_uuids: null,
      $topic: {},
    },
    {
      create_date: "2024-07-07T22:24:21.782Z",
      topic_id: "6",
      title: "Bishop John Shelby Spong",
      slug: "Bishop_John_Shelby_Spong",
      body: "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
      comment_count: "0",
      comment_count_max_create_date: "2024-07-19T04:36:35.761Z",
      edit: false,
      image_uuids: null,
      $topic: {},
    },
    {
      create_date: "2024-06-23T04:35:39.591Z",
      topic_id: "7",
      title: "Acceptance",
      slug: "Acceptance",
      body: "Christianity as it is today does not accept unrepentant atheists, with the exception of Unitarian Universalism, which prioritizes worship and reverence. This leaves little room for the type of pragmatic and deep discussion that can be had here.\n\nPerhaps here we can have a sanctuary, for those few of us who have something we wish to salvage from the wreckage that is Christianity's encounter with the modern age, some value that we seek to carry forward without the theistic baggage.",
      comment_count: "0",
      comment_count_max_create_date: "2024-07-19T04:36:35.761Z",
      edit: false,
      image_uuids: null,
      $topic: {},
    },
    {
      create_date: "2024-06-11T02:13:36.853Z",
      topic_id: "39",
      title: "Moderation",
      slug: "Moderation",
      body: "> Everything in moderation\n\n> — Cleobulus\n\nThe comments section here serves as an example of the type of moderation and threading that you will find on the topics on this site.\n\nAn AI will label any post that escalates, judges, or misunderstands.\n\nThe comments are still allowed, but others can rest easy with the AI absorbing the brunt of such tragic expressions of unmet needs.\n",
      comment_count: "0",
      comment_count_max_create_date: "2024-07-19T04:36:35.761Z",
      edit: false,
      image_uuids: null,
      $topic: {},
    },
  ],
  path: "/",
  activities: [],
  notifications: [],
};
