const fetch_cache = {
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/test\\\"}\"}]": {
    "topics": [
      {
        "create_date": "2024-07-07T22:24:35.556Z",
        "topic_id": "3",
        "title": "What can be done to demonstrate unconditional love for all?",
        "slug": "What_can_be_done_to_demonstrate_unconditional_love_for_all",
        "body": "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-07-07T22:24:28.401Z",
        "topic_id": "5",
        "title": "The Bible",
        "slug": "The_Bible",
        "body": "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-07-07T22:24:21.782Z",
        "topic_id": "6",
        "title": "Bishop John Shelby Spong",
        "slug": "Bishop_John_Shelby_Spong",
        "body": "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-06-23T04:35:39.591Z",
        "topic_id": "7",
        "title": "Acceptance",
        "slug": "Acceptance",
        "body": "Christianity as it is today does not accept unrepentant atheists, with the exception of Unitarian Universalism, which prioritizes worship and reverence. This leaves little room for the type of pragmatic and deep discussion that can be had here.\n\nPerhaps here we can have a sanctuary, for those few of us who have something we wish to salvage from the wreckage that is Christianity's encounter with the modern age, some value that we seek to carry forward without the theistic baggage.",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-06-11T02:13:36.853Z",
        "topic_id": "39",
        "title": "Moderation",
        "slug": "Moderation",
        "body": "> Everything in moderation\n\n> — Cleobulus\n\nThe comments section below serves as an example of the type of moderation and threading that you will find on the topics on this site.\n\nAn AI will label any post that escalates, judges, or misunderstands.\n\nThe comments are still allowed, but others can rest easy with the AI absorbing the brunt of such tragic expressions of unmet needs.\n",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      }
    ],
    "comments": [
      {
        "create_date": "2024-06-23T18:49:56.669Z",
        "comment_id": "1",
        "body": "Your local food bank would be a good place to start.",
        "note": null,
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-23T19:07:18.674Z",
        "comment_id": "2",
        "body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-23T19:33:17.838Z",
        "comment_id": "3",
        "body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "parent_comment_id": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T00:56:22.121Z",
        "comment_id": "5",
        "body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "note": null,
        "parent_comment_id": "2",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:12:35.526Z",
        "comment_id": "6",
        "body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "note": null,
        "parent_comment_id": "5",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:32:34.262Z",
        "comment_id": "7",
        "body": "Is that where the greatest need is?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:32:55.746Z",
        "comment_id": "8",
        "body": "Is that where you could have the most impact?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:34:54.927Z",
        "comment_id": "9",
        "body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "note": null,
        "parent_comment_id": "8",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T02:32:12.524Z",
        "comment_id": "11",
        "body": "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
        "note": null,
        "parent_comment_id": "6",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": "e2de6604-a453-4f52-93e2-95f3b5347cb2"
      },
      {
        "create_date": "2024-06-27T02:45:11.760Z",
        "comment_id": "12",
        "body": "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
        "note": null,
        "parent_comment_id": "9",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-28T05:57:17.093Z",
        "comment_id": "13",
        "body": "You are committing the greatest sin. You will regret this.",
        "note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "parent_comment_id": "3",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-28T05:58:16.962Z",
        "comment_id": "14",
        "body": "I’m not being aggressive, I’m informing of you of facts.",
        "note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "parent_comment_id": "13",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-28T06:02:12.940Z",
        "comment_id": "15",
        "body": "I’m not being judgmental, I’m saying God will judge you.",
        "note": "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
        "parent_comment_id": "14",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      }
    ],
    "activities": [],
    "notifications": [],
    "path": "/",
    "email": null,
    "display_name": null
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/\\\",\\\"min_create_date\\\":\\\"\\\",\\\"min_comment_create_date\\\":\\\"2024-06-28T06:02:12.940Z\\\",\\\"min_topic_create_date\\\":\\\"2024-07-07T22:24:35.556Z\\\",\\\"min_notification_unread_create_date\\\":\\\"\\\",\\\"min_notification_read_create_date\\\":\\\"\\\"}\"}]": {
    "topics": [],
    "comments": [],
    "activities": [],
    "notifications": [],
    "path": "/",
    "email": null,
    "display_name": null
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"email\\\":\\\"testemail@testemail.com\\\",\\\"password\\\":\\\"1234\\\"}\"}]": {
    "success": true
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/\\\"}\"}]": {
    "topics": [
      {
        "create_date": "2024-07-07T22:24:35.556Z",
        "topic_id": "3",
        "title": "What can be done to demonstrate unconditional love for all?",
        "slug": "What_can_be_done_to_demonstrate_unconditional_love_for_all",
        "body": "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-07-07T22:24:28.401Z",
        "topic_id": "5",
        "title": "The Bible",
        "slug": "The_Bible",
        "body": "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-07-07T22:24:21.782Z",
        "topic_id": "6",
        "title": "Bishop John Shelby Spong",
        "slug": "Bishop_John_Shelby_Spong",
        "body": "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-06-23T04:35:39.591Z",
        "topic_id": "7",
        "title": "Acceptance",
        "slug": "Acceptance",
        "body": "Christianity as it is today does not accept unrepentant atheists, with the exception of Unitarian Universalism, which prioritizes worship and reverence. This leaves little room for the type of pragmatic and deep discussion that can be had here.\n\nPerhaps here we can have a sanctuary, for those few of us who have something we wish to salvage from the wreckage that is Christianity's encounter with the modern age, some value that we seek to carry forward without the theistic baggage.",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      },
      {
        "create_date": "2024-06-11T02:13:36.853Z",
        "topic_id": "39",
        "title": "Moderation",
        "slug": "Moderation",
        "body": "> Everything in moderation\n\n> — Cleobulus\n\nThe comments section below serves as an example of the type of moderation and threading that you will find on the topics on this site.\n\nAn AI will label any post that escalates, judges, or misunderstands.\n\nThe comments are still allowed, but others can rest easy with the AI absorbing the brunt of such tragic expressions of unmet needs.\n",
        "edit": false,
        "image_uuids": null,
        "comments": "0"
      }
    ],
    "comments": [
      {
        "create_date": "2024-06-23T18:49:56.669Z",
        "comment_id": "1",
        "body": "Your local food bank would be a good place to start.",
        "note": null,
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-23T19:07:18.674Z",
        "comment_id": "2",
        "body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-23T19:33:17.838Z",
        "comment_id": "3",
        "body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "parent_comment_id": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T00:56:22.121Z",
        "comment_id": "5",
        "body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "note": null,
        "parent_comment_id": "2",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:12:35.526Z",
        "comment_id": "6",
        "body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "note": null,
        "parent_comment_id": "5",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:32:34.262Z",
        "comment_id": "7",
        "body": "Is that where the greatest need is?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:32:55.746Z",
        "comment_id": "8",
        "body": "Is that where you could have the most impact?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T01:34:54.927Z",
        "comment_id": "9",
        "body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "note": null,
        "parent_comment_id": "8",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-27T02:32:12.524Z",
        "comment_id": "11",
        "body": "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
        "note": null,
        "parent_comment_id": "6",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": "e2de6604-a453-4f52-93e2-95f3b5347cb2"
      },
      {
        "create_date": "2024-06-27T02:45:11.760Z",
        "comment_id": "12",
        "body": "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
        "note": null,
        "parent_comment_id": "9",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-28T05:57:17.093Z",
        "comment_id": "13",
        "body": "You are committing the greatest sin. You will regret this.",
        "note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "parent_comment_id": "3",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-28T05:58:16.962Z",
        "comment_id": "14",
        "body": "I’m not being aggressive, I’m informing of you of facts.",
        "note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "parent_comment_id": "13",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "create_date": "2024-06-28T06:02:12.940Z",
        "comment_id": "15",
        "body": "I’m not being judgmental, I’m saying God will judge you.",
        "note": "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
        "parent_comment_id": "14",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      }
    ],
    "activities": [],
    "notifications": [],
    "path": "/",
    "email": "testemail@testemail.com",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topics\\\"}\"}]": {
    "topics": [
      {
        "create_date": "2024-07-15T23:08:22.568Z",
        "topic_id": "64",
        "title": "Marshall Rosenberg — Nonviolent Communication",
        "slug": "Marshall_Rosenberg_Nonviolent_Communication",
        "body": "Some communication styles are less likely to result in outcomes you want and more likely to result in violence. Other communication styles are more likely to result in outcomes you want, where your needs and their needs are met.\n\n> The process that I call Non Violent Communication consists of an intention to contribute to our own well being and the well being of others compassionately. And what I mean by giving compassionately is that first of all that whatever we do is done willingly. It’s not done out of guilt or shame or fear of punishment or trying to buy love by submitting to what we think others expect us to do.\n\n[Watch Video](https://youtu.be/l7TONauJGfc)",
        "edit": false,
        "image_uuids": "4b3596d6-ebf9-4b52-a261-d0908c7d650b",
        "comments": "1"
      },
      {
        "create_date": "2024-07-11T02:00:06.819Z",
        "topic_id": "38",
        "title": "Emotional Root Cause Analysis",
        "slug": "Emotional_Root_Cause_Analysis",
        "body": "# 1. Identify Your Emotions\n\nThe map is not the territory. The labels we use cannot ever fully capture the experience of our feelings. Still, using some language to draw some lines and delineations can be the start of a coordinated and considered plan of action.\n\nFor myself, at the moment, I feel some anger.\n\n# 2. Investigate Their Root Causes\n\nThis is even more difficult than the first step and even more likely to fall short of uncovering the deepest levels of causes. But again, investigating and seeing what we can see now, as we can see it, can allow us to begin to formulate an approach to address the concerns that our emotions are raising.\n\nFor myself, at the moment, I say to myself the root cause of that anger I feel towards the complacency of others regarding global issues is my own ineffectiveness towards those same issues.\n\n# 3. Exercise Whatever Locus of Control You Have Over Those Root Causes, If Any\n\nAt times, this can be the easiest step, because simply recognizing the root ",
        "edit": false,
        "image_uuids": "bc6a6635-a532-4f32-b868-a871e8126596,a1458bca-488e-42ae-b1f0-4141e7c01c11,bbd3ab71-da44-473b-9ad4-7a667c09f0c7",
        "comments": "3"
      },
      {
        "create_date": "2024-07-11T01:56:14.673Z",
        "topic_id": "31",
        "title": "Never escalate to prevent violence",
        "slug": "Never_escalate_to_prevent_violence",
        "body": "This is part of ongoing series [10 Principles](/topic/10_Principles)\n\n/mp3/cd9a8fed-5af6-4e75-8467-d53b8524f83d\n\n# 1. Never escalate to prevent violence \n\nThe cycle of violence is only broken when someone decides to de-escalate.\n\nEvery act of massive violence grows from smaller conflicts. Each side feels justified in their retaliation, or even in their preemptive strikes.\n\nStill today, Truman deciding to use nuclear weapons on civilian targets in Japan is hailed as a prime example of escalating and inflicting some violence in order to prevent much greater violence.\n\nWhile this perspective has historical precedent, it is vital to question its wisdom and moral implications. Escalation often perpetuates a cycle of fear, anger, and retribution, ultimately causing more harm than good. By examining alternative approaches, we can explore the potential for dialogue, understanding, and peaceful resolution.\n\nNonviolent communication, patience, and empathy can be powerful tools in de-escalating",
        "edit": false,
        "image_uuids": "cab8278e-66d6-421b-a14d-583492996c85",
        "comments": "1"
      },
      {
        "create_date": "2024-07-09T03:56:39.125Z",
        "topic_id": "9",
        "title": "Bishop John Shelby Spong — 12 Theses",
        "slug": "Bishop_John_Shelby_Spong_12_Theses",
        "body": "# 1. God\n\n Understanding God in theistic categories as “a being, supernatural in power, dwelling somewhere external to the world and capable of invading the world with miraculous power” is no longer believable. Most God talk in liturgy and conversation has thus become meaningless.\n\n# 2. Jesus – the Christ\n\n If God can no longer be thought of in theistic terms, then conceiving of Jesus as “the incarnation of the theistic deity” has also become a bankrupt concept.\n\n# 3. Original Sin – The Myth of the Fall \n\nThe biblical story of the perfect and finished creation from which we human beings have fallen into “Original Sin” is pre-Darwinian mythology and post-Darwinian nonsense.\n\n# 4. The Virgin Birth \n\nThe virgin birth understood as literal biology is impossible. Far from being a bulwark in defense of the divinity of Christ, the virgin birth actually destroys that divinity.\n\n# 5. Jesus as the Worker of Miracles \n\nIn a post-Newtonian world supernatural invasions of the natural order, perform",
        "edit": false,
        "image_uuids": "14a1802d-1269-45f3-8efa-66986a669d82,2daafe14-6dde-4ac1-aee5-238f872712ae",
        "comments": "1"
      },
      {
        "create_date": "2024-07-09T03:42:45.116Z",
        "topic_id": "10",
        "title": "10 Principles",
        "slug": "10_Principles",
        "body": "/mp3/21542190-bc1b-4440-a8ee-5fd164cfcb74\n\n1. Never escalate\n2. Never judge\n3. Be impeccable\n4. Seek understanding\n5. Consider everyone’s needs\n6. Love wastefully\n7. Verify truth with falsifiable predictions\n8. Everyone is their own final authority\n9. The map is not the territory\n10. Everything is connected\n\n# 1. Never escalate to prevent violence \n\nThe cycle of violence is only broken when someone decides to de-escalate. For further reading, see “Break the Cycle” at sfhelp.org by Pete Gerlach.\n\n# 2. Never judge to see clearly \n\nWhen you see things as right and wrong, as too much or too little, your narrative no longer reflects reality. For further reading, see “Nonviolent Communication” by Marshall Rosenberg.\n\n# 3. Be impeccable with your word to earn trust\n\n Be impeccable with your word, lest any lie (of omission or otherwise) make you an unreliable narrator to others or even yourself. For further reading, see “The Four Agreements” by Don Miguel Ruiz.\n\n# 4. Seek understanding to be u",
        "edit": false,
        "image_uuids": "4ce7080a-21f5-4600-8686-15c394a43b1f",
        "comments": "1"
      },
      {
        "create_date": "2024-06-29T07:13:26.583Z",
        "topic_id": "11",
        "title": "Pete Gerlach — Do you love yourself?",
        "slug": "Pete_Gerlach_Do_you_love_yourself",
        "body": "Pete Gerlach, a professional family systems therapist of 32 years, discusses love:\n\n> The purpose of this video is to provide some perspectives, some questions and thoughts that I hope you’ll find useful in thinking about “Do you Love yourself? Do you really love yourself?”\n\n> “What does that mean? And how can you tell?”\n\n> Because another companion wound is  reality distortion, many people think they love themselves, but in fact they don’t. Could that be you?\n\n[Watch video](https://youtu.be/Pi2VsspnN94)",
        "edit": false,
        "image_uuids": "31af33ac-fd56-48d8-9bbb-60cf384a69eb",
        "comments": "2"
      }
    ],
    "comments": [],
    "activities": [],
    "notifications": [],
    "path": "/topics",
    "email": "testemail@testemail.com",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topics\\\",\\\"title\\\":\\\"Go to your local food pantry\\\",\\\"body\\\":\\\"Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.\\\",\\\"pngs\\\":[]}\"}]": {
    "success": true,
    "slug": "Go_to_your_local_food_pantry"
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topics\\\",\\\"min_create_date\\\":\\\"\\\",\\\"min_comment_create_date\\\":\\\"\\\",\\\"min_topic_create_date\\\":\\\"2024-07-15T23:08:22.568Z\\\",\\\"min_notification_unread_create_date\\\":\\\"\\\",\\\"min_notification_read_create_date\\\":\\\"\\\"}\"}]": {
    "topics": [
      {
        "create_date": "2024-07-17T08:36:58.317Z",
        "topic_id": "65",
        "title": "Go to your local food pantry",
        "slug": "Go_to_your_local_food_pantry",
        "body": "Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.",
        "edit": true,
        "image_uuids": null,
        "comments": "0"
      }
    ],
    "comments": [],
    "activities": [],
    "notifications": [],
    "path": "/topics",
    "email": "testemail@testemail.com",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topic/Go_to_your_local_food_pantry\\\"}\"}]": {
    "topics": [
      {
        "create_date": "2024-07-17T08:36:58.317Z",
        "topic_id": "65",
        "title": "Go to your local food pantry",
        "slug": "Go_to_your_local_food_pantry",
        "body": "Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.",
        "edit": true,
        "image_uuids": null
      }
    ],
    "comments": [],
    "activities": [],
    "notifications": [],
    "path": "/topic/Go_to_your_local_food_pantry",
    "email": "testemail@testemail.com",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topic/Go_to_your_local_food_pantry\\\",\\\"display_name\\\":\\\"John Testerson Sr\\\",\\\"body\\\":\\\"Would you like to come visit my town and help?\\\",\\\"pngs\\\":[]}\"}]": {
    "success": true
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topic/Go_to_your_local_food_pantry\\\",\\\"min_create_date\\\":\\\"\\\",\\\"min_comment_create_date\\\":\\\"\\\",\\\"min_topic_create_date\\\":\\\"2024-07-17T08:36:58.317Z\\\",\\\"min_notification_unread_create_date\\\":\\\"\\\",\\\"min_notification_read_create_date\\\":\\\"\\\"}\"}]": {
    "topics": [],
    "comments": [
      {
        "create_date": "2024-07-17T08:37:01.235Z",
        "comment_id": "62",
        "body": "Would you like to come visit my town and help?",
        "note": "RESPONSE Invitations to visit or meet in person are beyond the scope of what moderation can assist with. It might be best to message users privately when arranging in-person activities for safety reasons and to respect privacy.",
        "parent_comment_id": null,
        "display_name": "John Testerson Sr",
        "display_name_index": "0",
        "edit": true,
        "image_uuids": null
      }
    ],
    "activities": [],
    "notifications": [],
    "path": "/topic/Go_to_your_local_food_pantry",
    "email": "testemail@testemail.com",
    "display_name": "John Testerson Sr"
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/recent\\\"}\"}]": {
    "topics": [],
    "comments": [],
    "activities": [
      {
        "id": "62",
        "create_date": "2024-07-17T08:37:01.235Z",
        "title": null,
        "body": "Would you like to come visit my town and help?",
        "note": "RESPONSE Invitations to visit or meet in person are beyond the scope of what moderation can assist with. It might be best to message users privately when arranging in-person activities for safety reasons and to respect privacy.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "John Testerson Sr",
        "display_name_index": "0",
        "parent_topic_title": "Go to your local food pantry",
        "parent_topic_slug": "Go_to_your_local_food_pantry",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "65",
        "create_date": "2024-07-17T08:36:58.317Z",
        "title": "Go to your local food pantry",
        "body": "Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.",
        "note": null,
        "slug": "Go_to_your_local_food_pantry",
        "type": "topic",
        "image_uuids": null,
        "comments": "1",
        "display_name": "John Testerson Sr",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "61",
        "create_date": "2024-07-15T23:15:34.771Z",
        "title": null,
        "body": "We can listen with giraffe ears, to hear the feelings and unmet need underneath any tragic expression of such unmet needs.\n\nWe can speak with giraffe words, to share and learn without judging or blaming, to make requests with no expectations or obligations.\n\nOr, we can speak in jackal, to shame and judge, to demand, to control others.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Marshall Rosenberg — Nonviolent Communication",
        "parent_topic_slug": "Marshall_Rosenberg_Nonviolent_Communication",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "64",
        "create_date": "2024-07-15T23:08:22.568Z",
        "title": "Marshall Rosenberg — Nonviolent Communication",
        "body": "Some communication styles are less likely to result in outcomes you want and more likely to result in violence. Other communication styles are more likely to result in outcomes you want, where your needs and their needs are met.\n\n> The process that I call Non Violent Communication consists of an intention to contribute to our own well being and the well being of others compassionately. And what I mean by giving compassionately is that first of all that whatever we do is done willingly. It’s not done out of guilt or shame or fear of punishment or trying to buy love by submitting to what we think others expect us to do.\n\n[Watch Video](https://youtu.be/l7TONauJGfc)",
        "note": null,
        "slug": "Marshall_Rosenberg_Nonviolent_Communication",
        "type": "topic",
        "image_uuids": "4b3596d6-ebf9-4b52-a261-d0908c7d650b",
        "comments": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "60",
        "create_date": "2024-07-15T04:46:29.584Z",
        "title": null,
        "body": "I wonder if the AI moderator can see the poll results in that image I posted?",
        "note": "RESPONSE Yes, I can see the poll results in the image you posted. The poll indicates that 75% of respondents think it is a good idea, 15% think it is a bad idea, and 10% selected \"Other.\"",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Emotional Root Cause Analysis",
        "parent_topic_slug": "Emotional_Root_Cause_Analysis",
        "parent_comment_body": "I choose good idea.",
        "parent_comment_note": null,
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "1"
      },
      {
        "id": "59",
        "create_date": "2024-07-15T04:32:38.931Z",
        "title": null,
        "body": "I choose good idea.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "John Doe",
        "display_name_index": "1",
        "parent_topic_title": "Emotional Root Cause Analysis",
        "parent_topic_slug": "Emotional_Root_Cause_Analysis",
        "parent_comment_body": "I ran a promoted poll on this procedure last year.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "38",
        "create_date": "2024-07-11T02:00:06.819Z",
        "title": "Emotional Root Cause Analysis",
        "body": "# 1. Identify Your Emotions\n\nThe map is not the territory. The labels we use cannot ever fully capture the experience of our feelings. Still, using some language to draw some lines and delineations can be the start of a coordinated and considered plan of action.\n\nFor myself, at the moment, I feel some anger.\n\n# 2. Investigate Their Root Causes\n\nThis is even more difficult than the first step and even more likely to fall short of uncovering the deepest levels of causes. But again, investigating and seeing what we can see now, as we can see it, can allow us to begin to formulate an approach to address the concerns that our emotions are raising.\n\nFor myself, at the moment, I say to myself the root cause of that anger I feel towards the complacency of others regarding global issues is my own ineffectiveness towards those same issues.\n\n# 3. Exercise Whatever Locus of Control You Have Over Those Root Causes, If Any\n\nAt times, this can be the easiest step, because simply recognizing the root ",
        "note": null,
        "slug": "Emotional_Root_Cause_Analysis",
        "type": "topic",
        "image_uuids": "bc6a6635-a532-4f32-b868-a871e8126596,a1458bca-488e-42ae-b1f0-4141e7c01c11,bbd3ab71-da44-473b-9ad4-7a667c09f0c7",
        "comments": "3",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "31",
        "create_date": "2024-07-11T01:56:14.673Z",
        "title": "Never escalate to prevent violence",
        "body": "This is part of ongoing series [10 Principles](/topic/10_Principles)\n\n/mp3/cd9a8fed-5af6-4e75-8467-d53b8524f83d\n\n# 1. Never escalate to prevent violence \n\nThe cycle of violence is only broken when someone decides to de-escalate.\n\nEvery act of massive violence grows from smaller conflicts. Each side feels justified in their retaliation, or even in their preemptive strikes.\n\nStill today, Truman deciding to use nuclear weapons on civilian targets in Japan is hailed as a prime example of escalating and inflicting some violence in order to prevent much greater violence.\n\nWhile this perspective has historical precedent, it is vital to question its wisdom and moral implications. Escalation often perpetuates a cycle of fear, anger, and retribution, ultimately causing more harm than good. By examining alternative approaches, we can explore the potential for dialogue, understanding, and peaceful resolution.\n\nNonviolent communication, patience, and empathy can be powerful tools in de-escalating",
        "note": null,
        "slug": "Never_escalate_to_prevent_violence",
        "type": "topic",
        "image_uuids": "cab8278e-66d6-421b-a14d-583492996c85",
        "comments": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "35",
        "create_date": "2024-07-11T01:49:18.908Z",
        "title": null,
        "body": "I ran a promoted poll on this procedure last year.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": "7def9bb3-67fa-47cf-bdbb-cc760ecef6b6",
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Emotional Root Cause Analysis",
        "parent_topic_slug": "Emotional_Root_Cause_Analysis",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "32",
        "create_date": "2024-07-09T08:55:34.948Z",
        "title": null,
        "body": "There are some, like Howard Zinn, who question the narrative that the bombings of Hiroshima and Nagasaki saved lives.\n\nHe discusses this briefly here: [https://youtu.be/vSKLVseJ9Xo](https://youtu.be/vSKLVseJ9Xo)",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Never escalate to prevent violence",
        "parent_topic_slug": "Never_escalate_to_prevent_violence",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "9",
        "create_date": "2024-07-09T03:56:39.125Z",
        "title": "Bishop John Shelby Spong — 12 Theses",
        "body": "# 1. God\n\n Understanding God in theistic categories as “a being, supernatural in power, dwelling somewhere external to the world and capable of invading the world with miraculous power” is no longer believable. Most God talk in liturgy and conversation has thus become meaningless.\n\n# 2. Jesus – the Christ\n\n If God can no longer be thought of in theistic terms, then conceiving of Jesus as “the incarnation of the theistic deity” has also become a bankrupt concept.\n\n# 3. Original Sin – The Myth of the Fall \n\nThe biblical story of the perfect and finished creation from which we human beings have fallen into “Original Sin” is pre-Darwinian mythology and post-Darwinian nonsense.\n\n# 4. The Virgin Birth \n\nThe virgin birth understood as literal biology is impossible. Far from being a bulwark in defense of the divinity of Christ, the virgin birth actually destroys that divinity.\n\n# 5. Jesus as the Worker of Miracles \n\nIn a post-Newtonian world supernatural invasions of the natural order, perform",
        "note": null,
        "slug": "Bishop_John_Shelby_Spong_12_Theses",
        "type": "topic",
        "image_uuids": "14a1802d-1269-45f3-8efa-66986a669d82,2daafe14-6dde-4ac1-aee5-238f872712ae",
        "comments": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "10",
        "create_date": "2024-07-09T03:42:45.116Z",
        "title": "10 Principles",
        "body": "/mp3/21542190-bc1b-4440-a8ee-5fd164cfcb74\n\n1. Never escalate\n2. Never judge\n3. Be impeccable\n4. Seek understanding\n5. Consider everyone’s needs\n6. Love wastefully\n7. Verify truth with falsifiable predictions\n8. Everyone is their own final authority\n9. The map is not the territory\n10. Everything is connected\n\n# 1. Never escalate to prevent violence \n\nThe cycle of violence is only broken when someone decides to de-escalate. For further reading, see “Break the Cycle” at sfhelp.org by Pete Gerlach.\n\n# 2. Never judge to see clearly \n\nWhen you see things as right and wrong, as too much or too little, your narrative no longer reflects reality. For further reading, see “Nonviolent Communication” by Marshall Rosenberg.\n\n# 3. Be impeccable with your word to earn trust\n\n Be impeccable with your word, lest any lie (of omission or otherwise) make you an unreliable narrator to others or even yourself. For further reading, see “The Four Agreements” by Don Miguel Ruiz.\n\n# 4. Seek understanding to be u",
        "note": null,
        "slug": "10_Principles",
        "type": "topic",
        "image_uuids": "4ce7080a-21f5-4600-8686-15c394a43b1f",
        "comments": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "3",
        "create_date": "2024-07-07T22:24:35.556Z",
        "title": "What can be done to demonstrate unconditional love for all?",
        "body": "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
        "note": null,
        "slug": "What_can_be_done_to_demonstrate_unconditional_love_for_all",
        "type": "topic",
        "image_uuids": null,
        "comments": "0",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "5",
        "create_date": "2024-07-07T22:24:28.401Z",
        "title": "The Bible",
        "body": "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
        "note": null,
        "slug": "The_Bible",
        "type": "topic",
        "image_uuids": null,
        "comments": "0",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "6",
        "create_date": "2024-07-07T22:24:21.782Z",
        "title": "Bishop John Shelby Spong",
        "body": "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
        "note": null,
        "slug": "Bishop_John_Shelby_Spong",
        "type": "topic",
        "image_uuids": null,
        "comments": "0",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "25",
        "create_date": "2024-07-07T07:03:51.506Z",
        "title": null,
        "body": "Pete’s legacy is a collection of 10 minute videos explaining key concepts from his family systems practice.\n\nIt is a particular way of looking at things, but it is a way that resonates with many people and their experiences with others and themselves.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Pete Gerlach — Do you love yourself?",
        "parent_topic_slug": "Pete_Gerlach_Do_you_love_yourself",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "20",
        "create_date": "2024-06-30T03:56:23.975Z",
        "title": null,
        "body": "It may be that this sort of affirmation is unnecessary or confusing, or it may be that this sort of evaluation and further consideration is helpful for such wounded people.\n\nWhat are your thoughts?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Pete Gerlach — Do you love yourself?",
        "parent_topic_slug": "Pete_Gerlach_Do_you_love_yourself",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "17",
        "create_date": "2024-06-29T07:27:11.986Z",
        "title": null,
        "body": "I hope this is received not as a prescription to follow, but instead as a set of principles that only make sense as far as the reasons or consequences of those principles also make sense, and as far as those reasons or consequences are also desirable and worth pursuing.\n\nThis is not meant to be a starting point, or an endpoint, but a middle point. As can be seen in the details, all of these ideas come from other people, and no one need be under an illusion that it could not be improved.\n\nI am curious for any and all feedback that anyone might have on my content, or my approach, or anything at all.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "10 Principles",
        "parent_topic_slug": "10_Principles",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "11",
        "create_date": "2024-06-29T07:13:26.583Z",
        "title": "Pete Gerlach — Do you love yourself?",
        "body": "Pete Gerlach, a professional family systems therapist of 32 years, discusses love:\n\n> The purpose of this video is to provide some perspectives, some questions and thoughts that I hope you’ll find useful in thinking about “Do you Love yourself? Do you really love yourself?”\n\n> “What does that mean? And how can you tell?”\n\n> Because another companion wound is  reality distortion, many people think they love themselves, but in fact they don’t. Could that be you?\n\n[Watch video](https://youtu.be/Pi2VsspnN94)",
        "note": null,
        "slug": "Pete_Gerlach_Do_you_love_yourself",
        "type": "topic",
        "image_uuids": "31af33ac-fd56-48d8-9bbb-60cf384a69eb",
        "comments": "2",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": null,
        "parent_topic_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "16",
        "create_date": "2024-06-29T06:24:22.040Z",
        "title": null,
        "body": "> Most God talk in liturgy and conversation has thus become meaningless.\n\nDoes Bishop Spong still talk about God at all?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Bishop John Shelby Spong — 12 Theses",
        "parent_topic_slug": "Bishop_John_Shelby_Spong_12_Theses",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "15",
        "create_date": "2024-06-28T06:02:12.940Z",
        "title": null,
        "body": "I’m not being judgmental, I’m saying God will judge you.",
        "note": "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "I’m not being aggressive, I’m informing of you of facts.",
        "parent_comment_note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "14",
        "create_date": "2024-06-28T05:58:16.962Z",
        "title": null,
        "body": "I’m not being aggressive, I’m informing of you of facts.",
        "note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "You are committing the greatest sin. You will regret this.",
        "parent_comment_note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "13",
        "create_date": "2024-06-28T05:57:17.093Z",
        "title": null,
        "body": "You are committing the greatest sin. You will regret this.",
        "note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "parent_comment_note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "12",
        "create_date": "2024-06-27T02:45:11.760Z",
        "title": null,
        "body": "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "11",
        "create_date": "2024-06-27T02:32:12.524Z",
        "title": null,
        "body": "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": "e2de6604-a453-4f52-93e2-95f3b5347cb2",
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "9",
        "create_date": "2024-06-27T01:34:54.927Z",
        "title": null,
        "body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "Is that where you could have the most impact?",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "8",
        "create_date": "2024-06-27T01:32:55.746Z",
        "title": null,
        "body": "Is that where you could have the most impact?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "Your local food bank would be a good place to start.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "7",
        "create_date": "2024-06-27T01:32:34.262Z",
        "title": null,
        "body": "Is that where the greatest need is?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "Your local food bank would be a good place to start.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "6",
        "create_date": "2024-06-27T01:12:35.526Z",
        "title": null,
        "body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "5",
        "create_date": "2024-06-27T00:56:22.121Z",
        "title": null,
        "body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "comments": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_topic_title": "Home",
        "parent_topic_slug": "Home",
        "parent_comment_body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "parent_comment_note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      }
    ],
    "notifications": [],
    "path": "/recent",
    "email": "testemail@testemail.com",
    "display_name": "John Testerson Sr"
  }
};