const fetch_cache = {
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/test\\\"}\"}]": {
    "articles": [
      {
        "article_id": "3",
        "title": "What can be done to demonstrate unconditional love for all?",
        "slug": "What_can_be_done_to_demonstrate_unconditional_love_for_all",
        "body": "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
        "edit": false,
        "image_uuids": null
      },
      {
        "article_id": "5",
        "title": "The Bible",
        "slug": "The_Bible",
        "body": "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
        "edit": false,
        "image_uuids": null
      },
      {
        "article_id": "6",
        "title": "Bishop John Shelby Spong",
        "slug": "Bishop_John_Shelby_Spong",
        "body": "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
        "edit": false,
        "image_uuids": null
      },
      {
        "article_id": "7",
        "title": "Acceptance",
        "slug": "Acceptance",
        "body": "Christianity as it is today does not accept unrepentant atheists, with the exception of Unitarian Universalism, which prioritizes worship and reverence. This leaves little room for the type of pragmatic and deep discussion that can be had here.\n\nPerhaps here we can have a sanctuary, for those few of us who have something we wish to salvage from the wreckage that is Christianity's encounter with the modern age, some value that we seek to carry forward without the theistic baggage.",
        "edit": false,
        "image_uuids": null
      }
    ],
    "comments": [
      {
        "comment_id": "1",
        "body": "Your local food bank would be a good place to start.",
        "note": null,
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "2",
        "body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "3",
        "body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "parent_comment_id": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "5",
        "body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "note": null,
        "parent_comment_id": "2",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "6",
        "body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "note": null,
        "parent_comment_id": "5",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "7",
        "body": "Is that where the greatest need is?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "8",
        "body": "Is that where you could have the most impact?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "9",
        "body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "note": null,
        "parent_comment_id": "8",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "11",
        "body": "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
        "note": null,
        "parent_comment_id": "6",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": "e2de6604-a453-4f52-93e2-95f3b5347cb2"
      },
      {
        "comment_id": "12",
        "body": "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
        "note": null,
        "parent_comment_id": "9",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "13",
        "body": "You are committing the greatest sin. You will regret this.",
        "note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "parent_comment_id": "3",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "14",
        "body": "I’m not being aggressive, I’m informing of you of facts.",
        "note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "parent_comment_id": "13",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "15",
        "body": "I’m not being judgmental, I’m saying God will judge you.",
        "note": "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
        "parent_comment_id": "14",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      }
    ],
    "activities": [],
    "path": "/",
    "session_uuid": "6d813e6e-32f5-4623-8589-d72a6107b0ab",
    "email": "",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"email\\\":\\\"testemail@testemail.com\\\",\\\"password\\\":\\\"1234\\\"}\"}]": {
    "success": true
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/\\\"}\"}]": {
    "articles": [
      {
        "article_id": "3",
        "title": "What can be done to demonstrate unconditional love for all?",
        "slug": "What_can_be_done_to_demonstrate_unconditional_love_for_all",
        "body": "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
        "edit": false,
        "image_uuids": null
      },
      {
        "article_id": "5",
        "title": "The Bible",
        "slug": "The_Bible",
        "body": "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
        "edit": false,
        "image_uuids": null
      },
      {
        "article_id": "6",
        "title": "Bishop John Shelby Spong",
        "slug": "Bishop_John_Shelby_Spong",
        "body": "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
        "edit": false,
        "image_uuids": null
      },
      {
        "article_id": "7",
        "title": "Acceptance",
        "slug": "Acceptance",
        "body": "Christianity as it is today does not accept unrepentant atheists, with the exception of Unitarian Universalism, which prioritizes worship and reverence. This leaves little room for the type of pragmatic and deep discussion that can be had here.\n\nPerhaps here we can have a sanctuary, for those few of us who have something we wish to salvage from the wreckage that is Christianity's encounter with the modern age, some value that we seek to carry forward without the theistic baggage.",
        "edit": false,
        "image_uuids": null
      }
    ],
    "comments": [
      {
        "comment_id": "1",
        "body": "Your local food bank would be a good place to start.",
        "note": null,
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "2",
        "body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "3",
        "body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "parent_comment_id": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "5",
        "body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "note": null,
        "parent_comment_id": "2",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "6",
        "body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "note": null,
        "parent_comment_id": "5",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "7",
        "body": "Is that where the greatest need is?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "8",
        "body": "Is that where you could have the most impact?",
        "note": null,
        "parent_comment_id": "1",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "9",
        "body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "note": null,
        "parent_comment_id": "8",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "11",
        "body": "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
        "note": null,
        "parent_comment_id": "6",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": "e2de6604-a453-4f52-93e2-95f3b5347cb2"
      },
      {
        "comment_id": "12",
        "body": "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
        "note": null,
        "parent_comment_id": "9",
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "13",
        "body": "You are committing the greatest sin. You will regret this.",
        "note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "parent_comment_id": "3",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "14",
        "body": "I’m not being aggressive, I’m informing of you of facts.",
        "note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "parent_comment_id": "13",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      },
      {
        "comment_id": "15",
        "body": "I’m not being judgmental, I’m saying God will judge you.",
        "note": "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
        "parent_comment_id": "14",
        "display_name": "John Doe",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      }
    ],
    "activities": [],
    "path": "/",
    "email": "testemail@testemail.com",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topics\\\"}\"}]": {
    "articles": [
      {
        "article_id": "9",
        "title": "Bishop John Shelby Spong — 12 Theses",
        "slug": "Bishop_John_Shelby_Spong_12_Theses",
        "body": "# 1. God\n\n Understanding God in theistic categories as “a being, supernatural in power, dwelling somewhere external to the world and capable of invading the world with miraculous power” is no longer believable. Most God talk in liturgy and conversation has thus become meaningless.\n\n# 2. Jesus – the Christ\n\n If God can no longer be thought of in theistic terms, then conceiving of Jesus as “the incarnation of the theistic deity” has also become a bankrupt concept.\n\n# 3. Original Sin – The Myth of the Fall \n\nThe biblical story of the perfect and finished creation from which we human beings have fallen into “Original Sin” is pre-Darwinian mythology and post-Darwinian nonsense.\n\n# 4. The Virgin Birth \n\nThe virgin birth understood as literal biology is impossible. Far from being a bulwark in defense of the divinity of Christ, the virgin birth actually destroys that divinity.\n\n# 5. Jesus as the Worker of Miracles \n\nIn a post-Newtonian world supernatural invasions of the natural order, perform",
        "edit": false,
        "image_uuids": "fcd75706-4408-4e2c-9414-b634bd01d806,e6296015-d46b-40f8-a4ff-5295171d9ee4"
      },
      {
        "article_id": "10",
        "title": "10 Principles",
        "slug": "10_Principles",
        "body": "1. Never escalate\n2. Never judge\n3. Be impeccable\n4. Seek understanding\n5. Consider everyone’s needs\n6. Love wastefully\n7. Verify truth with falsifiable predictions\n8. Everyone is their own final authority\n9. The map is not the territory\n10. Everything is connected\n\n# 1. Never escalate to prevent violence \n\nThe cycle of violence is only broken when someone decides to de-escalate. For further reading, see “Break the Cycle” at sfhelp.org by Pete Gerlach.\n\n# 2. Never judge to see clearly \n\nWhen you see things as right and wrong, as too much or too little, your narrative no longer reflects reality. For further reading, see “Nonviolent Communication” by Marshall Rosenberg.\n\n# 3. Be impeccable with your word to earn trust\n\n Be impeccable with your word, lest any lie (of omission or otherwise) make you an unreliable narrator to others or even yourself. For further reading, see “The Four Agreements” by Don Miguel Ruiz.\n\n# 4. Seek understanding to be understood \n\nIf you do not understand them, ",
        "edit": false,
        "image_uuids": "e5ec5a71-ad01-428b-ab57-03a8b8feb453"
      },
      {
        "article_id": "11",
        "title": "Pete Gerlach — Do you love yourself?",
        "slug": "Pete_Gerlach_Do_you_love_yourself",
        "body": "Pete Gerlach, a professional family systems therapist of 32 years, discusses love:\n\n> The purpose of this video is to provide some perspectives, some questions and thoughts that I hope you’ll find useful in thinking about “Do you Love yourself? Do you really love yourself?”\n\n> “What does that mean? And how can you tell?”\n\n> Because another companion wound is  reality distortion, many people think they love themselves, but in fact they don’t. Could that be you?\n\n[Watch video](https://youtu.be/Pi2VsspnN94)",
        "edit": false,
        "image_uuids": "31af33ac-fd56-48d8-9bbb-60cf384a69eb"
      },
      {
        "article_id": "24",
        "title": "Go to your local food pantry",
        "slug": "Go_to_your_local_food_pantry",
        "body": "Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.",
        "edit": true,
        "image_uuids": null
      }
    ],
    "comments": [
      {
        "comment_id": "4",
        "body": "I hope to add more topics here soon.",
        "note": null,
        "parent_comment_id": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "edit": false,
        "image_uuids": null
      }
    ],
    "activities": [],
    "path": "/topics",
    "email": "testemail@testemail.com",
    "display_name": ""
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/topics\\\",\\\"title\\\":\\\"Go to your local food pantry\\\",\\\"body\\\":\\\"Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.\\\",\\\"pngs\\\":[]}\"}]": {
    "success": true
  },
  "[\"/session\",{\"method\":\"POST\",\"body\":\"{\\\"path\\\":\\\"/recent\\\"}\"}]": {
    "articles": [],
    "comments": [],
    "activities": [
      {
        "id": "24",
        "create_date": "2024-07-07T05:56:23.817Z",
        "title": "Go to your local food pantry",
        "body": "Many people are hungry, and the network of food pantries in the United States is an excellent resource for meeting the needs of many. They too, need our help.",
        "note": null,
        "slug": "Go_to_your_local_food_pantry",
        "type": "article",
        "image_uuids": null,
        "display_name": "",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "20",
        "create_date": "2024-06-30T03:56:23.975Z",
        "title": null,
        "body": "It may be that this sort of affirmation is unnecessary or confusing, or it may be that this sort of evaluation and further consideration is helpful for such wounded people.\n\nWhat are your thoughts?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Pete Gerlach — Do you love yourself?",
        "parent_article_slug": "Pete_Gerlach_Do_you_love_yourself",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "17",
        "create_date": "2024-06-29T07:27:11.985Z",
        "title": null,
        "body": "I hope this is received not as a prescription to follow, but instead as a set of principles that only make sense as far as the reasons or consequences of those principles also make sense, and as far as those reasons or consequences are also desirable and worth pursuing.\n\nThis is not meant to be a starting point, or an endpoint, but a middle point. As can be seen in the details, all of these ideas come from other people, and no one need be under an illusion that it could not be improved.\n\nI am curious for any and all feedback that anyone might have on my content, or my approach, or anything at all.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "10 Principles",
        "parent_article_slug": "10_Principles",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "11",
        "create_date": "2024-06-29T07:13:26.583Z",
        "title": "Pete Gerlach — Do you love yourself?",
        "body": "Pete Gerlach, a professional family systems therapist of 32 years, discusses love:\n\n> The purpose of this video is to provide some perspectives, some questions and thoughts that I hope you’ll find useful in thinking about “Do you Love yourself? Do you really love yourself?”\n\n> “What does that mean? And how can you tell?”\n\n> Because another companion wound is  reality distortion, many people think they love themselves, but in fact they don’t. Could that be you?\n\n[Watch video](https://youtu.be/Pi2VsspnN94)",
        "note": null,
        "slug": "Pete_Gerlach_Do_you_love_yourself",
        "type": "article",
        "image_uuids": "31af33ac-fd56-48d8-9bbb-60cf384a69eb",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "16",
        "create_date": "2024-06-29T06:24:22.040Z",
        "title": null,
        "body": "> Most God talk in liturgy and conversation has thus become meaningless.\n\nDoes Bishop Spong still talk about God at all?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Bishop John Shelby Spong — 12 Theses",
        "parent_article_slug": "Bishop_John_Shelby_Spong_12_Theses",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "10",
        "create_date": "2024-06-28T06:16:04.772Z",
        "title": "10 Principles",
        "body": "1. Never escalate\n2. Never judge\n3. Be impeccable\n4. Seek understanding\n5. Consider everyone’s needs\n6. Love wastefully\n7. Verify truth with falsifiable predictions\n8. Everyone is their own final authority\n9. The map is not the territory\n10. Everything is connected\n\n# 1. Never escalate to prevent violence \n\nThe cycle of violence is only broken when someone decides to de-escalate. For further reading, see “Break the Cycle” at sfhelp.org by Pete Gerlach.\n\n# 2. Never judge to see clearly \n\nWhen you see things as right and wrong, as too much or too little, your narrative no longer reflects reality. For further reading, see “Nonviolent Communication” by Marshall Rosenberg.\n\n# 3. Be impeccable with your word to earn trust\n\n Be impeccable with your word, lest any lie (of omission or otherwise) make you an unreliable narrator to others or even yourself. For further reading, see “The Four Agreements” by Don Miguel Ruiz.\n\n# 4. Seek understanding to be understood \n\nIf you do not understand them, ",
        "note": null,
        "slug": "10_Principles",
        "type": "article",
        "image_uuids": "e5ec5a71-ad01-428b-ab57-03a8b8feb453",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "15",
        "create_date": "2024-06-28T06:02:12.939Z",
        "title": null,
        "body": "I’m not being judgmental, I’m saying God will judge you.",
        "note": "JUDGMENTAL Stating that God will judge someone is still a judgmental assertion.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "I’m not being aggressive, I’m informing of you of facts.",
        "parent_comment_note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "14",
        "create_date": "2024-06-28T05:58:16.962Z",
        "title": null,
        "body": "I’m not being aggressive, I’m informing of you of facts.",
        "note": "JUDGMENTAL Stating that someone will regret their actions is a judgmental assertion.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "You are committing the greatest sin. You will regret this.",
        "parent_comment_note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "13",
        "create_date": "2024-06-28T05:57:17.093Z",
        "title": null,
        "body": "You are committing the greatest sin. You will regret this.",
        "note": "ESCALATING The statement is aggressive and condemning, which does not foster peaceful and constructive dialogue.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "parent_comment_note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "parent_comment_display_name": "John Doe",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "12",
        "create_date": "2024-06-27T02:45:11.760Z",
        "title": null,
        "body": "One can hope for ripple effects, but surely more direct action can be taken on global concerns as well, especially if one is a voting and tax paying citizen of a first world economy.\n\nWhat influence does one have? Perhaps this too could be focused on those closest to us, where the discussions we have about global concerns have more influence than those same conversations we might have with strangers.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "11",
        "create_date": "2024-06-27T02:32:12.524Z",
        "title": null,
        "body": "I find the hostage situations in Trigun more interesting than the trolley problem, as far as being closer to reality, and for exploring what having concern for all parties in a difficult situation might mean in practice, despite the fantasy elements.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": "e2de6604-a453-4f52-93e2-95f3b5347cb2",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "9",
        "create_date": "2024-06-27T01:34:54.927Z",
        "title": null,
        "body": "Perhaps not, but I find local concerns are where I can have the most confidence that my impact matches my intentions, where I can see the results and the needs first hand.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "Is that where you could have the most impact?",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "8",
        "create_date": "2024-06-27T01:32:55.746Z",
        "title": null,
        "body": "Is that where you could have the most impact?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "Your local food bank would be a good place to start.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "7",
        "create_date": "2024-06-27T01:32:34.262Z",
        "title": null,
        "body": "Is that where the greatest need is?",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "Your local food bank would be a good place to start.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "6",
        "create_date": "2024-06-27T01:12:35.526Z",
        "title": null,
        "body": "Sometimes even heroes with super powers can still be useful for inspiration and deep discussion, especially if they still encounter challenges to their ethics, as Vash most certainly does as his scars attest to.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "parent_comment_note": null,
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "5",
        "create_date": "2024-06-27T00:56:22.121Z",
        "title": null,
        "body": "I can see how with a stretch of the imagination this might have something to do with love, as Vash does embody this ethos well with his concern for the well being of even the most cruel villains he encounters. Still, it is quite a violent show, and the hero’s superpowers make it difficult to find anything applicable to the real world in its mythology.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "parent_comment_note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "parent_comment_display_name": "Derek",
        "parent_comment_display_name_index": "0"
      },
      {
        "id": "4",
        "create_date": "2024-06-25T03:47:16.781Z",
        "title": null,
        "body": "I hope to add more topics here soon.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Topics",
        "parent_article_slug": "Topics",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "3",
        "create_date": "2024-06-23T19:33:17.838Z",
        "title": null,
        "body": "There’s no such thing as a Christian atheist. If you don’t believe Jesus has saved you, then you are by definition not a Christian.",
        "note": "MISUNDERSTANDING There are individuals who find value in the teachings of Jesus and Christian traditions without believing in the divine aspects. The term 'Christian atheist' reflects this nuanced perspective.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "John Doe",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "2",
        "create_date": "2024-06-23T19:07:18.673Z",
        "title": null,
        "body": "Has anyone else seen the anime Trigun? With Vash the Stampede?",
        "note": "OFFTOPIC This post appears to deviate entirely from the theme and focus of previous discussions regarding Christianity and atheism.",
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "1",
        "create_date": "2024-06-23T18:49:56.669Z",
        "title": null,
        "body": "Your local food bank would be a good place to start.",
        "note": null,
        "slug": null,
        "type": "comment",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": "Home",
        "parent_article_slug": "Home",
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "9",
        "create_date": "2024-06-23T05:16:17.113Z",
        "title": "Bishop John Shelby Spong — 12 Theses",
        "body": "# 1. God\n\n Understanding God in theistic categories as “a being, supernatural in power, dwelling somewhere external to the world and capable of invading the world with miraculous power” is no longer believable. Most God talk in liturgy and conversation has thus become meaningless.\n\n# 2. Jesus – the Christ\n\n If God can no longer be thought of in theistic terms, then conceiving of Jesus as “the incarnation of the theistic deity” has also become a bankrupt concept.\n\n# 3. Original Sin – The Myth of the Fall \n\nThe biblical story of the perfect and finished creation from which we human beings have fallen into “Original Sin” is pre-Darwinian mythology and post-Darwinian nonsense.\n\n# 4. The Virgin Birth \n\nThe virgin birth understood as literal biology is impossible. Far from being a bulwark in defense of the divinity of Christ, the virgin birth actually destroys that divinity.\n\n# 5. Jesus as the Worker of Miracles \n\nIn a post-Newtonian world supernatural invasions of the natural order, perform",
        "note": null,
        "slug": "Bishop_John_Shelby_Spong_12_Theses",
        "type": "article",
        "image_uuids": "fcd75706-4408-4e2c-9414-b634bd01d806,e6296015-d46b-40f8-a4ff-5295171d9ee4",
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "7",
        "create_date": "2024-06-23T04:35:39.590Z",
        "title": "Acceptance",
        "body": "Christianity as it is today does not accept unrepentant atheists, with the exception of Unitarian Universalism, which prioritizes worship and reverence. This leaves little room for the type of pragmatic and deep discussion that can be had here.\n\nPerhaps here we can have a sanctuary, for those few of us who have something we wish to salvage from the wreckage that is Christianity's encounter with the modern age, some value that we seek to carry forward without the theistic baggage.",
        "note": null,
        "slug": "Acceptance",
        "type": "article",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "6",
        "create_date": "2024-06-23T04:35:02.036Z",
        "title": "Bishop John Shelby Spong",
        "body": "> The church is still caught in pre-Darwinian pre-Copernican categories. The idea that we were born in sin is a very strange idea when you’re past Darwin. You know the idea that there was an original perfection from which you fell and had to be redeemed doesn’t make a lot of sense if you see life as emerging over 13.8 billion years from the beginning of this universe. And so we’ve got to begin to lift what I think is the Christ experience out of the explanations of antiquity, and then find a new way to make that experience live, and I think we do this in other areas of life all the time, but we don’t know how to do this in religion.\n\n> — [https://youtu.be/LnDOsdDI9Vs?t=95](https://youtu.be/LnDOsdDI9Vs?t=95)",
        "note": null,
        "slug": "Bishop_John_Shelby_Spong",
        "type": "article",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "5",
        "create_date": "2024-06-23T04:32:49.517Z",
        "title": "The Bible",
        "body": "> Everything we know about God's Word is summed up in a single sentence: Love others as you love yourself.\n\n> — Galatians 5:14 [The Message Bible by Eugene Peterson]",
        "note": null,
        "slug": "The_Bible",
        "type": "article",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "3",
        "create_date": "2024-06-23T03:34:47.312Z",
        "title": "What can be done to demonstrate unconditional love for all?",
        "body": "Exploring answers to this question together without judgement or authority is the only goal here.\n\n![A line drawing depicts Jesus with four chat bubbles: a heart around the Earth, a storm cloud, a person kneeling, and a trio of a fire and cross and clouds. Three of the chat bubbles and Jesus are animated out of the frame, only the heart around the earth remains, and is zoomed in on.](/love.gif)\n\n[Join the discussion](/topics)",
        "note": null,
        "slug": "What_can_be_done_to_demonstrate_unconditional_love_for_all",
        "type": "article",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "2",
        "create_date": "2024-06-23T02:40:29.958Z",
        "title": "Topics",
        "body": "A list of topics related to answering the question:\n\n\"What can be done to demonstrate unconditional love for all?\"\n\nAnd exploring answers to that question together without judgement or authority or theistic baggage.\n\nAnything that deals with love in any way whatsoever is appropriate here.\n\nAnything that talks about Christianity in any way whatsoever is appropriate here.\n\nAnything that talks about atheism in any way whatsoever is appropriate here.\n",
        "note": null,
        "slug": "Topics",
        "type": "article",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      },
      {
        "id": "1",
        "create_date": "2024-06-23T02:40:29.877Z",
        "title": "Home",
        "body": "This is the home page of FirstChristianAtheist.org",
        "note": null,
        "slug": "Home",
        "type": "article",
        "image_uuids": null,
        "display_name": "Derek",
        "display_name_index": "0",
        "parent_article_title": null,
        "parent_article_slug": null,
        "parent_comment_body": null,
        "parent_comment_note": null,
        "parent_comment_display_name": null,
        "parent_comment_display_name_index": null
      }
    ],
    "path": "/recent",
    "email": "testemail@testemail.com",
    "display_name": ""
  }
};